package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class escenaPrincipalController {
	@FXML
	private Label labMensaje;

	// Event Listener on Button.onAction
	@FXML
	public void btnPresionado(ActionEvent event) {
		// TODO Autogenerated
		labMensaje.setText("Hola Mundo :D ");
	}
}
